// list data
export const PricesItem = [
	{
		id: 0,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "up",
		route: "dashboard/prices/0",
	},
	{
		id: 1,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "",
		route: "dashboard/prices/1",
	},
	{
		id: 2,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "up",
		route: "dashboard/prices/2",
	},
	{
		id: 3,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "",
		route: "dashboard/prices/3",
	},
	{
		id: 4,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "down",
		route: "dashboard/prices/4",
	},
	{
		id: 5,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "",
		route: "dashboard/prices/5",
	},
	{
		id: 6,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "up",
		route: "dashboard/prices/6",
	},
	{
		id: 7,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "down",
		route: "dashboard/prices/7",
	},
	{
		id: 8,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "up",
		route: "dashboard/prices/8",
	},
	{
		id: 9,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "up",
		route: "dashboard/prices/9",
	},
	{
		id: 10,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "down",
		route: "dashboard/prices/10",
	},
	{
		id: 11,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "up",
		route: "dashboard/prices/11",
	},
	{
		id: 12,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "up",
		route: "dashboard/prices/12",
	},
	{
		id: 13,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "down",
		route: "dashboard/prices/13",
	},
	{
		id: 14,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "up",
		route: "dashboard/prices/14",
	},
	{
		id: 15,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "down",
		route: "dashboard/prices/15",
	},
	{
		id: 16,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "up",
		route: "dashboard/prices/16",
	},
	{
		id: 17,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "up",
		route: "dashboard/prices/17",
	},
	{
		id: 18,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "down",
		route: "dashboard/prices/18",
	},
	{
		id: 19,
		title: "DE-lu Day Base",
		unit: 112.75,
		indicator: "up",
		route: "dashboard/prices/19",
	},
];

export const PFCGas = [
	{
		id: 1,
		title: "Gas PFC Cyclic",
		route: "dashboard/pfc/1",
	},
	{
		id: 2,
		title: "Gas PFC aCyclic",
		route: "dashboard/pfc/2",
	},
];
export const PFCStrom = [
	{
		id: 10,
		title: "Power PFC Externe Strom (Stabdard)",
		route: "dashboard/pfc/10",
	},
	{
		id: 20,
		title: "Power PFC Externe Strom (Grun)",
		route: "dashboard/pfc/20",
	},
	{
		id: 30,
		title: "Power PFC Continuous",
		route: "dashboard/pfc/30",
	},
	{
		id: 40,
		title: "Power PFC Elektrik Turkey",
		route: "dashboard/pfc/40",
	},
	{
		id: 50,
		title: "Power PFC HUPX",
		route: "dashboard/pfc/50",
	},
];
export const SignalsGas = [
	{
		id: 1,
		title: "Gas Cal+1",
		route: "dashboard/signals/1",
	},
	{
		id: 2,
		title: "Gas Cal+2",
		route: "dashboard/signals/2",
	},
	{
		id: 3,
		title: "Gas Cal+3",
		route: "dashboard/signals/3",
	},
	{
		id: 4,
		title: "Gas Q+1",
		route: "dashboard/signals/4",
		notificationCount: 1,
	},
	{
		id: 5,
		title: "Gas Q+2",
		route: "dashboard/signals/5",
	},
	{
		id: 6,
		title: "Gas Q+3",
		route: "dashboard/signals/6",
	},
	{
		id: 7,
		title: "Gas Q+4",
		route: "dashboard/signals/7",
	},
];
export const SignalsStrom = [
	{
		id: 10,
		title: "Power Cal+1 Base",
		route: "dashboard/signals/10",
	},
	{
		id: 20,
		title: "Power Cal+1 Peak",
		route: "dashboard/signals/20",
	},
	{
		id: 30,
		title: "Power Cal+2 Base",
		route: "dashboard/signals/30",
	},
	{
		id: 40,
		title: "Power Cal+2 Peak",
		route: "dashboard/signals/40",
	},
	{
		id: 50,
		title: "Power Cal+3 Base",
		route: "dashboard/signals/50",
	},
	{
		id: 60,
		title: "Power Cal+3 Peak",
		route: "dashboard/signals/60",
	},
	{
		id: 70,
		title: "Power Q+1 Base",
		route: "dashboard/signals/70",
	},
	{
		id: 80,
		title: "Power Q+1 Peak",
		route: "dashboard/signals/80",
	},
	{
		id: 90,
		title: "Power Q+2 Base",
		route: "dashboard/signals/90",
	},
	{
		id: 100,
		title: "Power Q+2 Peak",
		route: "dashboard/signals/100",
	},
	{
		id: 120,
		title: "Power Q+3 Base",
		route: "dashboard/signals/120",
	},
	{
		id: 13,
		title: "Power Q+3 Peak",
		route: "dashboard/signals/130",
	},
	{
		id: 140,
		title: "Power Q+4 Base",
		route: "dashboard/signals/140",
	},
	{
		id: 150,
		title: "Power Q+4 Peak",
		route: "dashboard/signal/150",
	},
];
export const signalsCards: any = [
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
	{
		title: "BB EEX HGas Cal Base + 1",
		data: {
			lowSoft: 10,
			lowHard: 5,
			negative: "No",
			highSoft: 20,
			highHard: 30,
			days: 20,
		},
	},
	{
		title: "RSI EEX HGas Cal Base + 1",
		data: {
			lowSoft: 20,
			lowHard: 10,
			negative: "No",
			highSoft: 80,
			highHard: 90,
			days: 10,
		},
	},
];
