// list data
export const PricesItem = [
    {
        id: 0,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "up",
        route: "dashboard/prices/0",
    },
    {
        id: 1,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "",
        route: "dashboard/prices/1",
    },
    {
        id: 2,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "up",
        route: "dashboard/prices/2",
    },
    {
        id: 3,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "",
        route: "dashboard/prices/3",
    },
    {
        id: 4,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "down",
        route: "dashboard/prices/4",
    },
    {
        id: 5,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "",
        route: "dashboard/prices/5",
    },
    {
        id: 6,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "up",
        route: "dashboard/prices/6",
    },
    {
        id: 7,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "down",
        route: "dashboard/prices/7",
    },
    {
        id: 8,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "up",
        route: "dashboard/prices/8",
    },
    {
        id: 9,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "up",
        route: "dashboard/prices/9",
    },
    {
        id: 10,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "down",
        route: "dashboard/prices/10",
    },
    {
        id: 11,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "up",
        route: "dashboard/prices/11",
    },
    {
        id: 12,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "up",
        route: "dashboard/prices/12",
    },
    {
        id: 13,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "down",
        route: "dashboard/prices/13",
    },
    {
        id: 14,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "up",
        route: "dashboard/prices/14",
    },
    {
        id: 15,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "down",
        route: "dashboard/prices/15",
    },
    {
        id: 16,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "up",
        route: "dashboard/prices/16",
    },
    {
        id: 17,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "up",
        route: "dashboard/prices/17",
    },
    {
        id: 18,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "down",
        route: "dashboard/prices/18",
    },
    {
        id: 19,
        title: "DE-lu Day Base",
        unit: 112.75,
        indicator: "up",
        route: "dashboard/prices/19",
    },
];

export const gasItems = [
    {
        id: 1,
        title: "Gas 2021 NCG-H",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2021,
    },
    {
        id: 2,
        title: "Gas 2021 NCG-L",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2021,
    },
    {
        id: 3,
        title: "Gas 2022 Swing",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2022,
    },
    {
        id: 4,
        title: "Gas 2022 NCG-H",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2022,
    },

    {
        id: 7,
        title: "Gas 2023 NCG-H",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2023,
    },
    {
        id: 8,
        title: "Gas 2023 NCG-L",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2023,
    },

    {
        id: 12,
        title: "Gas 2024 Swing",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2024,
    },
    {
        id: 13,
        title: "Gas 2024 NCG-H",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2024,
    },
    {
        id: 14,
        title: "Gas 2024 NCG-L",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2024,
    },
    {
        id: 15,
        title: "Gas 2024 Swing",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2024,
    },
    {
        id: 16,
        title: "Gas 2025 Swing",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2025,
    },
    {
        id: 17,
        title: "Gas 2025 NCG-L",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2025,
    },
    {
        id: 18,
        title: "Gas 2025 Swing",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2025,
    },
    {
        id: 19,
        title: "Gas 2025 Swing",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2025,
    },
    {
        id: 20,
        title: "Gas 2025 Swing",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2025,
    },
    {
        id: 21,
        title: "Gas 2026 Swing",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2026,
    },
    {
        id: 22,
        title: "Gas 2027 Swing",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2027,
    },
    {
        id: 23,
        title: "Gas 2027 Swing",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2027,
    },
    {
        id: 24,
        title: "Gas 2027 Swing",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2027,
    },
];
export const powerItems = [
    {
        id: 10,
        title: "Strom 2021",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2021,
    },
    {
        id: 20,
        title: "Strom 2021 Swing",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2021,
    },

    {
        id: 50,
        title: "Strom 2022 Swing",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2022,
    },
    {
        id: 60,
        title: "Strom 2022",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2022,
    },

    {
        id: 90,
        title: "Strom 2023",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2023,
    },
    {
        id: 100,
        title: "Strom 2023",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2023,
    },

    {
        id: 130,
        title: "Strom 2024",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2024,
    },
    {
        id: 140,
        title: "Strom 2024",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2024,
    },
    {
        id: 150,
        title: "Strom 2024",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2024,
    },
    {
        id: 180,
        title: "Strom 2025 ",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2025,
    },
    {
        id: 190,
        title: "Strom 2025 ",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2025,
    },
    {
        id: 200,
        title: "Strom 2025 ",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2025,
    },
    {
        id: 201,
        title: "Strom 2025 ",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2025,
    },
    {
        id: 202,
        title: "Strom 2026 ",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2026,
    },
    {
        id: 203,
        title: "Strom 2026 ",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2026,
    },
    {
        id: 2033,
        title: "Strom 2026 ",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2026,
    },
    {
        id: 1920,
        title: "Strom 2027 ",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2027,
    },
    {
        id: 1690,
        title: "Strom 2027 ",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2027,
    },
    {
        id: 163290,
        title: "Strom 2027 ",
        route: "dashboard/portfolio/portfolio-overview",
        year: 2027,
    },
];
export const DashboardCardsEng = [
    {
        id: 1,
        title: "prices",
        icon: "PRICES",
        notificationCount: 0,
        route: "dashboard/(tabs)/prices",
    },
    {
        id: 2,
        title: "pfc",
        icon: "PFC",
        notificationCount: 0,
        route: "dashboard/(tabs)/pfc",
    },
    {
        id: 3,
        title: "loaddata",
        icon: "LOAD",
        notificationCount: 0,
        route: "dashboard/(tabs)/loaddata",
    },
    {
        id: 4,
        title: "signals",
        icon: "SIGNALS",
        notificationCount: 3,
        route: "dashboard/(tabs)/signals",
    },
    {
        id: 5,
        title: "portfolio",
        icon: "PORTFOLIO",
        notificationCount: 0,
        route: "dashboard/(tabs)/portfolio",
    },
    {
        id: 6,
        title: "settings",
        icon: "SETTINGS",
        notificationCount: 0,
        route: "dashboard/settings",
    },
];
export const AccordionData = [
    {
        id: "10",
        title: "Summenlastgänge | BILSTEIN GmbH & Co. KG",
        details: [
            {
                id: 0,
                channel: "Gas| BILSTEIN GmbH & Co. KG | Summenlastgänge",
                route: "/dashboard/loaddata/0/0",
            },
        ],
    },
    {
        id: "11",
        title: "Gas | BILSTEIN GmbH & Co. KG | 58119 Hagen",
        details: [
            {
                id: 1,
                channel:
                    "Werk I - Virtuell (Summe aus Bilstein Im Weinhof + Färberstr.) | MaLo: 50603374899 | Quelle: Kunde",
                route: "/dashboard/loaddata/1",
            },
            {
                id: 2,
                channel:
                    "Werk II - Oeger Str. 11-35 | MaLo: 50601507997 | Quelle: Kunde",
                route: "/dashboard/loaddata/2",
            },
            {
                id: 3,
                channel:
                    "Werk II - Oeger Str. 24 | MaLo: 50603613437 | Quelle: Kunde",
                route: "/dashboard/loaddata/3",
            },
            {
                id: 4,
                channel:
                    "Werk II - Oeger Str. 24 | MaLo: 50603613437 | Quelle: Kunde",
                route: "/dashboard/loaddata/4",
            },
        ],
    },
    {
        id: "12",
        title: "Gas | HUGO VOGELSANG GmbH & Co. KG | 58119 Hagen",
        details: [
            {
                id: 5,
                channel: "Alemannenweg 29 | MaLo: 50603613578 | Quelle: kunde",
                route: "/dashboard/loaddata/5",
            },
        ],
    },
    {
        id: "13",
        title: "Gas | BILSTEIN GmbH & Co. KG | 58093 Hagen",
        details: [],
    },
];
export const PFCGas = [
    {
        id: 1,
        title: "Gas PFC Cyclic",
        route: "dashboard/pfc/1",
    },
    {
        id: 2,
        title: "Gas PFC aCyclic",
        route: "dashboard/pfc/2",
    },
];
export const PFCStrom = [
    {
        id: 10,
        title: "Power PFC Externe Strom (Stabdard)",
        route: "dashboard/pfc/10",
    },
    {
        id: 20,
        title: "Power PFC Externe Strom (Grun)",
        route: "dashboard/pfc/20",
    },
    {
        id: 30,
        title: "Power PFC Continuous",
        route: "dashboard/pfc/30",
    },
    {
        id: 40,
        title: "Power PFC Elektrik Turkey",
        route: "dashboard/pfc/40",
    },
    {
        id: 50,
        title: "Power PFC HUPX",
        route: "dashboard/pfc/50",
    },
];
export const SignalsGas = [
    {
        id: 1,
        title: "Gas Cal+1",
        route: "dashboard/signals/1",
    },
    {
        id: 2,
        title: "Gas Cal+2",
        route: "dashboard/signals/2",
    },
    {
        id: 3,
        title: "Gas Cal+3",
        route: "dashboard/signals/3",
    },
    {
        id: 4,
        title: "Gas Q+1",
        route: "dashboard/signals/4",
        notificationCount: 1,
    },
    {
        id: 5,
        title: "Gas Q+2",
        route: "dashboard/signals/5",
    },
    {
        id: 6,
        title: "Gas Q+3",
        route: "dashboard/signals/6",
    },
    {
        id: 7,
        title: "Gas Q+4",
        route: "dashboard/signals/7",
    },
];
export const SignalsStrom = [
    {
        id: 10,
        title: "Power Cal+1 Base",
        route: "dashboard/signals/10",
    },
    {
        id: 20,
        title: "Power Cal+1 Peak",
        route: "dashboard/signals/20",
    },
    {
        id: 30,
        title: "Power Cal+2 Base",
        route: "dashboard/signals/30",
    },
    {
        id: 40,
        title: "Power Cal+2 Peak",
        route: "dashboard/signals/40",
    },
    {
        id: 50,
        title: "Power Cal+3 Base",
        route: "dashboard/signals/50",
    },
    {
        id: 60,
        title: "Power Cal+3 Peak",
        route: "dashboard/signals/60",
    },
    {
        id: 70,
        title: "Power Q+1 Base",
        route: "dashboard/signals/70",
    },
    {
        id: 80,
        title: "Power Q+1 Peak",
        route: "dashboard/signals/80",
    },
    {
        id: 90,
        title: "Power Q+2 Base",
        route: "dashboard/signals/90",
    },
    {
        id: 100,
        title: "Power Q+2 Peak",
        route: "dashboard/signals/100",
    },
    {
        id: 120,
        title: "Power Q+3 Base",
        route: "dashboard/signals/120",
    },
    {
        id: 13,
        title: "Power Q+3 Peak",
        route: "dashboard/signals/130",
    },
    {
        id: 140,
        title: "Power Q+4 Base",
        route: "dashboard/signals/140",
    },
    {
        id: 150,
        title: "Power Q+4 Peak",
        route: "dashboard/signal/150",
    },
];
export const signalsCards: any = [
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
    {
        title: "BB EEX HGas Cal Base + 1",
        data: {
            lowSoft: 10,
            lowHard: 5,
            negative: "No",
            highSoft: 20,
            highHard: 30,
            days: 20,
        },
    },
    {
        title: "RSI EEX HGas Cal Base + 1",
        data: {
            lowSoft: 20,
            lowHard: 10,
            negative: "No",
            highSoft: 80,
            highHard: 90,
            days: 10,
        },
    },
];
export const portfolioCards = [
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "26/03/2020",
        price: "41.56 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "07/04/2020",
        price: "46.1 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "26/03/2020",
        price: "41.56 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "07/04/2020",
        price: "46.1 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "26/03/2020",
        price: "41.56 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "07/04/2020",
        price: "46.1 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "26/03/2020",
        price: "41.56 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "07/04/2020",
        price: "46.1 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "26/03/2020",
        price: "41.56 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "07/04/2020",
        price: "46.1 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "26/03/2020",
        price: "41.56 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "07/04/2020",
        price: "46.1 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "26/03/2020",
        price: "41.56 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "07/04/2020",
        price: "46.1 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "26/03/2020",
        price: "41.56 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "07/04/2020",
        price: "46.1 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "26/03/2020",
        price: "41.56 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "07/04/2020",
        price: "46.1 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "26/03/2020",
        price: "41.56 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "07/04/2020",
        price: "46.1 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "26/03/2020",
        price: "41.56 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "07/04/2020",
        price: "46.1 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "26/03/2020",
        price: "41.56 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "07/04/2020",
        price: "46.1 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "26/03/2020",
        price: "41.56 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "07/04/2020",
        price: "46.1 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "26/03/2020",
        price: "41.56 €/MWh",
        state: "Confirmed",
    },
    {
        title: "2024 Cal Base",
        direction: "Buy",
        trader: "RheinEnergie",
        amount: "1 MW",
        date: "07/04/2020",
        price: "46.1 €/MWh",
        state: "Confirmed",
    },
];
