import { Translations } from "@/types/type";

export const TranslationKeys: Translations | any = {
  en: {
    unit: "kWh",
    tooltip: "Tooltip",
    xaxisUnit: "Date / Time",
    Month: " Month",
    Week: " Week",
    Day: " Day",
    Year: "Year",
    Quarter: "Quarter",
    show: "Show Chart",
    January: "January",
    February: "February",
    March: "March",
    April: "April",
    May: "May",
    June: "June",
    July: "July",
    August: "August",
    September: "September",
    October: "October",
    November: "November",
    December: "December",
    All: "All",
    comingsoon: "Coming Soon!",
    login: "login",
    logout: "logout",
    forgotyourpassword: "Forgot your password?",
    prices: "prices",
    pfc: "PFC",
    loaddata: "load data",
    load: "load data",
    signals: "signals",
    portfolio: "portfolio",
    settings: "settings",
    start: "start",
    marketinfo: "Market Info",
    consumption: "consumption",
    feedback: "feedback",
    rateus: "rate us",
    contactus: "contact us",
    visitwebsite: "visit website",
    imprintLegalNotes: "Imprint & Legal Notes",
    imprint: "imprint",
    termsConditions: "Terms & Conditions",
    privacypolicy: "Privacy Policy",
    We_re_working_hard_to_bring_you_something_amazing:
      "We're working hard to bring you something amazing.",
    language: "Language",
    notifications: "Notifications",
    save: "save",
    cancel: "cancel",
    send: "send",
    show_notifications: "Show Notifications",
    how_is_your_experience_with_our_app_so_far:
      "How is your experience with our app so far?",
    what_could_we_improve: "What could we improve?",
    name: "Name",
    phone: "Phone",
    email: "Email",
    message: "Message",
    poor: "Poor",
    below_average: "Below Average",
    fair: "Fair",
    almost_average: "Almost Average",
    average: "Average",
    above_average: "Above Average",
    good: "Good",
    very_good: "Very Good",
    excellent: "Excellent",
    datetime: "Date / Time",
    Energy: "Energy",
    Average: "Average",
    Customize_View: "Customize View",
    View_Signal_Settings: "View Signal Settings",
    View_Signal_Chart: "View Signal Chart",
    Load_Data_Details: "Load Data Details",
    Please_enter_your_username_and_password:
      "Please enter your username and password.",
    Please_enter_your_username: "Please enter your username.",
    Please_enter_your_password: "Please enter your password.",
    Username_should_not_contain_special_characters:
      "Username should not contain special characters.",
    An_error_occurred_Please_try_again: "An error occurred. Please try again.",
    username: "Username",
    password: "Password",
    Enter_your_registered_email_address_to_reset_your_password:
      "Enter your registered email address to reset your password.",
    "Login failed. Please try again.": "Login failed. Please try again.",
    portfolio_overview: "Portfolio Overview",
  },
  de: {
    unit: "kWh",
    tooltip: "Tooltip",
    xaxisUnit: "Datum / Uhrzeit",
    Month: " Monat",
    Week: " Woche",
    Day: " Tag",
    Year: "Jahr",
    Quarter: "Quartal",
    show: "Chart Anzeigen",
    January: "Januar",
    February: "Februar",
    March: "Marsch",
    April: "April",
    May: "Mai",
    June: "Juni",
    July: "Juli",
    August: "August",
    September: "September",
    October: "Oktober",
    November: "November",
    December: "Dezember",
    All: "Alle",
    comingsoon: "Bald erhältlich!",
    login: "anmelden",
    logout: "Abmelden",
    forgotyourpassword: "Passwort vergessen?",
    PRICES: "preise",
    pfc: "PFC",
    loaddata: "lastdaten",
    load: "lastdaten",
    signals: "Signale",
    portfolio: "portfolio",
    settings: "Einstellungen",
    start: "start",
    marketinfo: "Marktdaten",
    consumption: "Verbrauchdaten",
    feedback: "feedback",
    rateus: "Bewerten Sie uns",
    contactus: "Kontaktieren Sie uns",
    visitwebsite: "Unsere Website",
    imprintLegalNotes: "Impressum und rechtliches",
    imprint: "Impressum",
    termsConditions: "AGB",
    privacypolicy: "Datenschutzerklarung",
    We_re_working_hard_to_bring_you_something_amazing:
      "Wir arbeiten hart daran, Ihnen etwas Erstaunliches zu bieten.",
    language: "Sprache",
    notifications: "mitteilungen",
    save: "SPEICHERN",
    cancel: "abbrechen",
    send: "Schicken",
    show_notifications: "mitteilungen anzeigen",
    how_is_your_experience_with_our_app_so_far:
      "Wie Wurden Sie lhre bisheringe Erfahrung mit unserer App bewerten?",
    what_could_we_improve: "Was konnten wir verbessern?",
    name: "Name",
    phone: "Telefon",
    email: "E-Mail",
    message: "Ihre Nachricht",
    poor: "Schlecht",
    below_average: "Unterdurchschnittlich",
    fair: "Fair",
    almost_average: "Beinahe Durchschnittlich",
    average: "Durchschnittlich",
    above_average: "Überdurchschnittlich",
    good: "Gut",
    very_good: "Sehr Gut",
    excellent: "Ausgezeichnet",
    datetime: "Datum / Uhrzeit",
    Energy: "Energie",
    Average: "Durchschnitt",
    Customize_View: "Ansicht anpassen",
    View_Signal_Settings: "Signal Einstellungen anzeigen",
    View_Signal_Chart: "Signal Einstellungen anzeigen",
    Load_Data_Details: "Details Lastdaten",
    Please_enter_your_username_and_password:
      "Bitte geben Sie Ihren Benutzernamen und Ihr Passwort ein.",
    Please_enter_your_username: "Bitte geben Sie Ihren Benutzernamen ein.",
    Please_enter_your_password: "Bitte geben Sie Ihr Passwort ein.",
    Username_should_not_contain_special_characters:
      "Der Benutzername sollte keine Sonderzeichen enthalten.",
    An_error_occurred_Please_try_again:
      "Es ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.",
    username: "Benutzername",
    password: "Passwort",
    Enter_your_registered_email_address_to_reset_your_password:
      "Geben Sie Ihre registrierte E-Mail-Adresse ein, um Ihr Passwort zurückzusetzen.",
    "Login failed. Please try again.":
      "Anmeldung fehlgeschlagen. Bitte versuche es erneut.",
    portfolio_overview: "Portfolio Übersicht",
  },
};
